export const actionTypes = {
    TRIGGER_MODAL: 'TRIGGER_MODAL',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    POST_MOVIE_SUCCESS: 'POST_MOVIE_SUCCESS',
    UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
    DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
    SORT_MOVIE_SUCCESS: 'SORT_MOVIE_SUCCESS',
    FILTER_MOVIE_SUCCESS: 'FILTER_MOVIE_SUCCESS',
}